
var bulk_data = [{ parameter: "typeOfEstablishment", text: "Establishment Type", children: [
{ text: "Other Independent School" },
{ text: "Voluntary Aided School" },
{ text: "Foundation School" },
{ text: "Community School" },
{ text: "Other Independent Special School" },
{ text: "Community Special School" },
{ text: "LA Nursery School" },
{ text: "Pupil Referral Unit" },
{ text: "City Technology College" },
{ text: "Voluntary Controlled School" },
{ text: "Independent School Approved for SEN Pupils" },
{ text: "Foundation Special School" },
{ text: "Miscellaneous" },
{ text: "Non-Maintained Special School" },
{ text: "Academies" },
{ text: "Legacy types" },
{ text: "Playing for Success Centres" },
{ text: "Further Education" },
{ text: "Institution funded by other Government Department" },
{ text: "Service Childrens Education" },
{ text: "Secure Units" },
{ text: "European Schools" },
{ text: "Offshore Schools" },
{ text: "Sixth Form Centres" },
{ text: "Special College" },
{ text: "Higher Education Institutions" },
{ text: "Welsh Establishment" },
{ text: "EY Setting" }]
},

{ parameter: "districtAdministrative", text: "District", children: [
{ text: "Southwark" },
{ text: "Lambeth" },
{ text: "Westminster" },
{ text: "Kensington and Chelsea" },
{ text: "Wandsworth" },
{ text: "Milton Keynes" },
{ text: "Thanet" },
{ text: "Barking and Dagenham" },
{ text: "Barnet" },
{ text: "Lewisham" },
{ text: "Bromley" },
{ text: "Greenwich" },
{ text: "Tower Hamlets" },
{ text: "Lewes" },
{ text: "Bexley" },
{ text: "Brent" },
{ text: "Enfield" },
{ text: "Birmingham" },
{ text: "Waltham Forest" },
{ text: "Coventry" },
{ text: "Solihull" },
{ text: "Stratford-on-Avon" },
{ text: "Bromsgrove" },
{ text: "Wirral" },
{ text: "St. Helens" },
{ text: "Liverpool" },
{ text: "Knowsley" },
{ text: "Wolverhampton" },
{ text: "South Staffordshire" },
{ text: "Sefton" },
{ text: "Telford and Wrekin" },
{ text: "Bolton" },
{ text: "Bury" },
{ text: "Salford" },
{ text: "Manchester" },
{ text: "Oldham" },
{ text: "Macclesfield" },
{ text: "Congleton" },
{ text: "Chorley" },
{ text: "Rochdale" },
{ text: "Stockport" },
{ text: "High Peak" },
{ text: "Trafford" },
{ text: "Tameside" },
{ text: "Wigan" },
{ text: "Barnsley" },
{ text: "Doncaster" },
{ text: "Rotherham" },
{ text: "Sheffield" },
{ text: "Bradford" },
{ text: "Leeds" },
{ text: "Harrogate" },
{ text: "Calderdale" },
{ text: "Kirklees" },
{ text: "North Tyneside" },
{ text: "North Somerset" },
{ text: "Bath and North East Somerset" },
{ text: "South Gloucestershire" },
{ text: "Bristol, City of" },
{ text: "Isles of Scilly" },
{ text: "Mid Bedfordshire" },
{ text: "Sunderland" },
{ text: "South Tyneside" },
{ text: "Newcastle upon Tyne" },
{ text: "Luton" },
{ text: "Bedford" },
{ text: "West Somerset" },
{ text: "Broxtowe" },
{ text: "Thurrock" },
{ text: "Sedgefield" },
{ text: "South Bedfordshire" },
{ text: "Reading" },
{ text: "Windsor and Maidenhead" },
{ text: "West Berkshire" },
{ text: "Wokingham" },
{ text: "Slough" },
{ text: "Bracknell Forest" },
{ text: "Merton" },
{ text: "South Somerset" },
{ text: "Aylesbury Vale" },
{ text: "South Bucks" },
{ text: "Chiltern" },
{ text: "Wycombe" },
{ text: "Fenland" },
{ text: "Peterborough" },
{ text: "Huntingdonshire" },
{ text: "South Cambridgeshire" },
{ text: "Cambridge" },
{ text: "East Cambridgeshire" },
{ text: "Chester" },
{ text: "Ellesmere Port & Neston" },
{ text: "Halton" },
{ text: "Vale Royal" },
{ text: "Warrington" },
{ text: "Crewe and Nantwich" },
{ text: "King's Lynn and West Norfolk" },
{ text: "Redcar and Cleveland" },
{ text: "Carrick" },
{ text: "Kerrier" },
{ text: "Penwith" },
{ text: "Stockton-on-Tees" },
{ text: "Hartlepool" },
{ text: "Middlesbrough" },
{ text: "Allerdale" },
{ text: "South Lakeland" },
{ text: "Barrow-in-Furness" },
{ text: "Carlisle" },
{ text: "Copeland" },
{ text: "Eden" },
{ text: "Derbyshire Dales" },
{ text: "Derby" },
{ text: "Amber Valley" },
{ text: "Bolsover" },
{ text: "North East Derbyshire" },
{ text: "Erewash" },
{ text: "Chesterfield" },
{ text: "South Derbyshire" },
{ text: "Derwentside" },
{ text: "Easington" },
{ text: "Wear Valley" },
{ text: "Darlington" },
{ text: "Durham" },
{ text: "Teesdale" },
{ text: "Chester-le-Street" },
{ text: "North Dorset" },
{ text: "Poole" },
{ text: "Bournemouth" },
{ text: "Weymouth and Portland" },
{ text: "West Dorset" },
{ text: "East Dorset" },
{ text: "Purbeck" },
{ text: "Christchurch" },
{ text: "Wealden" },
{ text: "Brighton and Hove" },
{ text: "Rother" },
{ text: "Hastings" },
{ text: "Eastbourne" },
{ text: "Braintree" },
{ text: "Colchester" },
{ text: "Tendring" },
{ text: "Southend-on-Sea" },
{ text: "Harlow" },
{ text: "Chelmsford" },
{ text: "Rochford" },
{ text: "Uttlesford" },
{ text: "Maldon" },
{ text: "Epping Forest" },
{ text: "Castle Point" },
{ text: "Basildon" },
{ text: "Brentwood" },
{ text: "Forest of Dean" },
{ text: "Cotswold" },
{ text: "Tewkesbury" },
{ text: "Gloucester" },
{ text: "Stroud" },
{ text: "Cheltenham" },
{ text: "Portsmouth" },
{ text: "Gosport" },
{ text: "Southampton" },
{ text: "Basingstoke and Deane" },
{ text: "East Hampshire" },
{ text: "Rushmoor" },
{ text: "Test Valley" },
{ text: "Eastleigh" },
{ text: "Havant" },
{ text: "New Forest" },
{ text: "Fareham" },
{ text: "Winchester" },
{ text: "Hart" },
{ text: "Malvern Hills" },
{ text: "Wyre Forest" },
{ text: "Worcester" },
{ text: "Herefordshire, County of" },
{ text: "Wychavon" },
{ text: "Redditch" },
{ text: "Kingston upon Hull, City of" },
{ text: "East Hertfordshire" },
{ text: "East Riding of Yorkshire" },
{ text: "Hillingdon" },
{ text: "Burnley" },
{ text: "North Lincolnshire" },
{ text: "North East Lincolnshire" },
{ text: "Hertsmere" },
{ text: "Stevenage" },
{ text: "North Hertfordshire" },
{ text: "St Albans" },
{ text: "Dacorum" },
{ text: "Three Rivers" },
{ text: "Welwyn Hatfield" },
{ text: "Watford" },
{ text: "Broxbourne" },
{ text: "Gravesham" },
{ text: "Ashford" },
{ text: "Medway" },
{ text: "Dover" },
{ text: "Canterbury" },
{ text: "Swale" },
{ text: "Tonbridge and Malling" },
{ text: "Tunbridge Wells" },
{ text: "Dartford" },
{ text: "Sevenoaks" },
{ text: "Maidstone" },
{ text: "Shepway" },
{ text: "Hyndburn" },
{ text: "Lancaster" },
{ text: "Pendle" },
{ text: "West Lancashire" },
{ text: "Preston" },
{ text: "Blackburn with Darwen" },
{ text: "Rossendale" },
{ text: "Wyre" },
{ text: "Fylde" },
{ text: "South Ribble" },
{ text: "Blackpool" },
{ text: "Ribble Valley" },
{ text: "Leicester" },
{ text: "Blaby" },
{ text: "Melton" },
{ text: "North West Leicestershire" },
{ text: "Harborough" },
{ text: "Charnwood" },
{ text: "Hinckley and Bosworth" },
{ text: "Oadby and Wigston" },
{ text: "Rutland" },
{ text: "South Kesteven" },
{ text: "Lincoln" },
{ text: "East Lindsey" },
{ text: "Boston" },
{ text: "North Kesteven" },
{ text: "South Holland" },
{ text: "West Lindsey" },
{ text: "Broadland" },
{ text: "Norwich" },
{ text: "Great Yarmouth" },
{ text: "Breckland" },
{ text: "North Norfolk" },
{ text: "South Norfolk" },
{ text: "Scarborough" },
{ text: "Hambleton" },
{ text: "Ryedale" },
{ text: "York" },
{ text: "Selby" },
{ text: "Craven" },
{ text: "Richmondshire" },
{ text: "Kettering" },
{ text: "Wellingborough" },
{ text: "Northampton" },
{ text: "Hackney" },
{ text: "Daventry" },
{ text: "South Northamptonshire" },
{ text: "East Northamptonshire" },
{ text: "Corby" },
{ text: "Nottingham" },
{ text: "Bassetlaw" },
{ text: "Ashfield" },
{ text: "Mansfield" },
{ text: "Gedling" },
{ text: "Newark and Sherwood" },
{ text: "Rushcliffe" },
{ text: "Oxford" },
{ text: "Vale of White Horse" },
{ text: "West Oxfordshire" },
{ text: "Cherwell" },
{ text: "South Oxfordshire" },
{ text: "North Shropshire" },
{ text: "South Shropshire" },
{ text: "Shrewsbury and Atcham" },
{ text: "Bridgnorth" },
{ text: "Oswestry" },
{ text: "Sedgemoor" },
{ text: "Mendip" },
{ text: "Taunton Deane" },
{ text: "Stoke-on-Trent" },
{ text: "Cannock Chase" },
{ text: "Newcastle-under-Lyme" },
{ text: "Nuneaton and Bedworth" },
{ text: "Croydon" },
{ text: "East Staffordshire" },
{ text: "Lichfield" },
{ text: "Staffordshire Moorlands" },
{ text: "Stafford" },
{ text: "Tamworth" },
{ text: "Ipswich" },
{ text: "Woking" },
{ text: "Waverley" },
{ text: "Elmbridge" },
{ text: "Runnymede" },
{ text: "Reigate and Banstead" },
{ text: "Mole Valley" },
{ text: "Guildford" },
{ text: "Epsom and Ewell" },
{ text: "Spelthorne" },
{ text: "Tandridge" },
{ text: "Surrey Heath" },
{ text: "Sutton" },
{ text: "Mid Suffolk" },
{ text: "Babergh" },
{ text: "Waveney" },
{ text: "St Edmundsbury" },
{ text: "Suffolk Coastal" },
{ text: "Forest Heath" },
{ text: "Mid Sussex" },
{ text: "Horsham" },
{ text: "Chichester" },
{ text: "Adur" },
{ text: "Worthing" },
{ text: "Arun" },
{ text: "Crawley" },
{ text: "Salisbury" },
{ text: "North Wiltshire" },
{ text: "Kennet" },
{ text: "West Wiltshire" },
{ text: "Swindon" },
{ text: "Camden" },
{ text: "Hammersmith and Fulham" },
{ text: "Redbridge" },
{ text: "Islington" },
{ text: "Ealing" },
{ text: "Haringey" },
{ text: "Havering" },
{ text: "Hounslow" },
{ text: "Newham" },
{ text: "Richmond upon Thames" },
{ text: "Dudley" },
{ text: "Sandwell" },
{ text: "Walsall" },
{ text: "Denbighshire" },
{ text: "Sir Ddinbych" },
{ text: "Tynedale" },
{ text: "Gateshead" },
{ text: "Wakefield" },
{ text: "Castle Morpeth" },
{ text: "Wansbeck" },
{ text: "Isle of Wight" },
{ text: "Plymouth" },
{ text: "Torbay" },
{ text: "Exeter" },
{ text: "Restormel" },
{ text: "Harrow" },
{ text: "Rugby" },
{ text: "North Warwickshire" },
{ text: "Warwick" },
{ text: "Kingston upon Thames" },
{ text: "Monmouthshire" },
{ text: "Sir Fynwy" },
{ text: "Berwick-upon-Tweed" },
{ text: "East Devon" },
{ text: "Torridge" },
{ text: "Fife" },
{ text: "Perth & Kinross" },
{ text: "Dumfries & Galloway" },
{ text: "Blyth Valley" },
{ text: "Teignbridge" },
{ text: "Caradon" },
{ text: "Edinburgh, City of" },
{ text: "Cardiff" },
{ text: "Caerdydd" },
{ text: "South Hams" },
{ text: "North Devon" },
{ text: "North Cornwall" },
{ text: "City of London" },
{ text: "Wrexham" },
{ text: "Wrecsam" },
{ text: "Falkirk" },
{ text: "Rhondda, Cynon, Taff" },
{ text: "Rhondda Cynon Taf" },
{ text: "Merthyr Tydfil" },
{ text: "Merthyr Tudful" },
{ text: "Caerphilly" },
{ text: "Caerffili" },
{ text: "Ynys Mu201Cn" },
{ text: "Isle of Anglesey" },
{ text: "Gwynedd" },
{ text: "Conwy" },
{ text: "Flintshire" },
{ text: "Sir y Fflint" },
{ text: "Powys" },
{ text: "Ceredigion" },
{ text: "Sir Ceredigion" },
{ text: "Sir Benfro" },
{ text: "Pembrokeshire" },
{ text: "Carmarthenshire" },
{ text: "Sir Gaerfyrddin" },
{ text: "Swansea" },
{ text: "Abertawe" },
{ text: "Neath Port Talbot" },
{ text: "Castell-nedd Port Talbot" },
{ text: "Bridgend" },
{ text: "Pen-y-bont ar Ogwr" },
{ text: "The Vale of Glamorgan" },
{ text: "Bro Morgannwg" },
{ text: "Alnwick" },
{ text: "Mid Devon" },
{ text: "West Devon" },
{ text: "West Lothian" },
{ text: "Newport" },
{ text: "Casnewydd" },
{ text: "Torfaen" },
{ text: "Tor-faen" },
{ text: "Blaenau Gwent" },
{ text: "Aberdeen City" }
]
},

{ parameter: "phaseOfEducation", text: "Phase", children: [
  { text: "Primary"},
  { text: "Secondary"},
  { text: "Nursery"},
  { text: "Middle Deemed Secondary"},
  { text: "Middle Deemed Primary"},
  { text: "16 Plus"},
  { text: "Not applicable"}
]
}];